name: Chronos
options:
  bundleIdPrefix: com.example
targets:
  Chronos:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - Chronos.xcodeproj
          - project.yml
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.Chronos
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "Automatic"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
schemes:
  Chronos:
    build:
      targets:
        Chronos: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
